"""
pwb_readme.py
-------------
A synthetic README in the shape ``web_sources.parse_pwb_readme`` reads, and the
page as the fetcher would hand it over, for the tests of the ingest job.

The paperswithbacktest repository publishes no licence, so nothing here is its
text. Every title is invented for the purpose; the figures beside them are
sentinels, numbers no title holds, so one surviving into an excerpt would be
seen; and the lines around the table are only the shape the parser reads: the
generator's markers, its note, the level-two headings and the five-column
table, with a heading and a table outside the markers that must not be read.
"""

from __future__ import annotations

import hashlib
from collections.abc import Iterable, Sequence
from datetime import UTC, datetime

from src.programme import web_sources
from src.programme.web_fetch import Fetched

SOURCE = web_sources.ALLOWED_SOURCES["pwb-readme"]

START_LINE = "<!-- STRATEGIES:START - generated by a synthetic script -->"
HEADER = "| Strategy | Sharpe | t-stat | Volatility | Years tested |"
DELIMITER = "|---|---|---|---|---|"
STRATEGY_PAGE = "https://paperswithbacktest.com/strategies/"

#: Figures no invented title contains.
FIGURES = ("7.13", "91.7", "38.6%", "4242")

#: Invented titles, one list per heading. None is a real paper's title.
TITLES: dict[str, list[str]] = {
    "Equities": [
        "Quiet Momentum in Invented Mid-Cap Shares",
        "The Weekday Drift of Imaginary Small Firms",
    ],
    "Bonds": ["Term Spreads and the Patient Fictional Lender"],
    "Commodities": ["Seasonal Carry in Made-Up Grain Futures"],
    "Currencies": ["Volatility Timing Across Imaginary Pairs"],
    "Cryptocurrencies": ["Order Flow Imbalance in Pretend Token Venues"],
    "Derivatives": ["Skew Premia in Fictional Index Options"],
    "Multi-asset": ["Risk Budgeting With Made-Up Regime Signals"],
}


def row(title: str, slug: str = "an-invented-strategy") -> str:
    """One table row as the generator writes one: a linked title, four figures."""
    sharpe, t_stat, volatility, years = FIGURES
    return (
        f"| [{title}]({STRATEGY_PAGE}{slug}) | `{sharpe}` | `{t_stat}` | "
        f"`{volatility}` | `{years}` |"
    )


def sections(
    titles: dict[str, list[str]] | None = None,
) -> list[tuple[str, list[str]]]:
    """Each heading with its rows, from ``titles`` (by default :data:`TITLES`)."""
    chosen = TITLES if titles is None else titles
    return [
        (heading, [row(title, f"slug-{n}") for n, title in enumerate(listed)])
        for heading, listed in chosen.items()
    ]


def readme(
    parts: Iterable[tuple[str, Sequence[str]]] | None = None,
    *,
    before_table: Sequence[str] = (),
) -> str:
    """
    A README with the table between the markers, and outside them what the
    parser must never read: another ``## Crypto`` heading and a table of its
    own, before the markers and after them. ``before_table`` goes inside the
    markers, before the first heading, where only the generator's note may be.
    """
    block: list[str] = [
        "*An invented note on how the table below was generated.*",
        "",
        *before_table,
    ]
    for heading, rows in sections() if parts is None else parts:
        block += [f"## {heading}", "", HEADER, DELIMITER, *rows, ""]
    outside = [
        "## Crypto",
        "",
        HEADER,
        DELIMITER,
        row("An Outside Row That Must Not Be Read", "outside"),
        "",
    ]
    return "\n".join(
        [
            "# An Invented Awesome List",
            "",
            *outside,
            "# Strategies",
            "",
            START_LINE,
            "",
            *block,
            web_sources.END_MARKER,
            "",
            "# Books",
            "",
            *outside,
        ]
    )


def fetched(text: str) -> Fetched:
    """``text`` as ``web_fetch.fetch`` returns a page it fetched whole."""
    body = text.encode("utf-8")
    return Fetched(
        source=SOURCE,
        text=text,
        sha256=hashlib.sha256(body).hexdigest(),
        bytes=len(body),
        fetched_at=datetime.now(UTC),
    )
